apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nodejs-nojcsoue
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-nojcsoue 
  name: nodejs-nojcsoue
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: nodejs-nojcsoue 
